'''
Exercise 11: Process an LLM Response

Problem:
Your application receives this LLM response:

llm_response = {
    "model": "gpt-5",
    "status": "success",
    "message": {
        "role": "assistant",
        "content": "Python dictionaries store data using key-value pairs."
    },
    "usage": {
        "prompt_tokens": 12,
        "completion_tokens": 10
    }
}

Your program needs to extract the assistant's response.

Print only the content generated by the assistant.

Expected Output:
Python dictionaries store data using key-value pairs.
'''

# solution
llm_response = {
    "model": "gpt-5",
    "status": "success",
    "message": {
        "role": "assistant",
        "content": "Python dictionaries store data using key-value pairs."
    },
    "usage": {
        "prompt_tokens": 12,
        "completion_tokens": 10
    }
}

print(llm_response["message"]["content"])

